[package]
name = "tutorial"
version = "0.1.0"
authors = ["Vlad Frolov <frolvlad@gmail.com>"]
edition = "2018"

[build-dependencies]
flatc-rust = { path = "../../" }

[dependencies]
flatbuffers = "22.9.29"
